baseURL = 'https://juliand.ax/'
languageCode = 'en-us'
title = 'Julian Dax'
theme = 'terminal'



[languages]
  [languages.en]
    languageName = "English"
    title = "Julian Dax"
    subtitle = "Software Engineer and Programming Language Enthusiast"
    owner = "Julian Dax"
    keywords = ["Javascript", "Typescript"]
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "Julian Dax"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "profile"
        name = "Profile"
        url = "/profile"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"
[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = "jdax"
  site = "jdax"
